services:
  - type: web
    name: aidar-dashboard
    env: python
    region: frankfurt
    plan: free
    
    buildCommand: |
      pip install -r requirements.txt
    
    startCommand: |
      gunicorn --workers 1 --worker-class sync --bind 0.0.0.0:$PORT app:server
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      - key: PORT
        value: 8050

  - type: cron
    name: daily-data-updater
    schedule: "0 6 * * *"
    command: "python data_updater.py"
